version: '3'
services:
  app:
    container_name: kotlin
    build:
      context: .docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ./gradlew bootRun